apiVersion: v1
kind: Service
metadata:
  name: moove-kibana-srv
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: moove-kibana
  ports:
  - port: 5601
    targetPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: moove-kibana-nodeport
spec:
  type: NodePort
  selector:
    app: moove-kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30560

