---
# Source: logstash/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moove-logstash
  namespace: "default"
  labels:
    app.kubernetes.io/instance: moove
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: logstash
    app.kubernetes.io/version: 8.15.0
    helm.sh/chart: logstash-6.3.2
automountServiceAccountToken: false
