apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moove-kafka-ss
spec:
  selector:
    matchLabels:
      app: moove-kafka
  serviceName: moove-kafka-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: moove-kafka
    spec:
      containers:
        - name: moove-kafka-cont
          image: bitnami/kafka:latest
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"

            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"

            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"

            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"

            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@moove-kafka-srv:9093"

            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://moove-kafka-srv:9092"

            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          ports:
            - containerPort: 9092
            - containerPort: 9093
          
          volumeMounts:
            - name: moove-kafka-data
              mountPath: /bitnami
  volumeClaimTemplates:
    - metadata:
        name: moove-kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
