apiVersion: apps/v1
kind: Deployment
metadata:
  name: moove-logger-depl
spec:
  selector:
    matchLabels:
      app: moove-logger
  template:
    metadata:
      labels:
        app: moove-logger
      annotations:
        co.elastic.logs/json.overwrite_keys: "true" 
        co.elastic.logs/json.add_error_key: "true" 
        co.elastic.logs/json.expand_keys: "true" 
    spec:
      containers:
        - name: moove-logger-cont
          image: faridmansimli/moove-logger
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
          ports:
            - containerPort: 3001
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: PORT
              value: "3001"

            - name: KAFKA_URI
              value: "moove-kafka-srv:9092"

            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: "1"

            - name: ELASTICSEARCH_HOST
              value: "moove-elasticsearch"
            
            - name: ELASTICSEARCH_PORT
              value: "9200"

            - name: ELASTICSEARCH_URL
              value: "http://$(ELASTICSEARCH_HOST):$(ELASTICSEARCH_PORT)"

            - name: LOGSTASH_HOST
              value: "moove-logstash"
            
            - name: LOGSTASH_HTTP_HOST
              value: "http://$(LOGSTASH_HTTP_HOST)"
            
            - name: LOGSTASH_HTTP_PORT
              value: "8080"
