FROM node:20-alpine
WORKDIR /moove-logger

COPY package*.json ./
RUN npm install

RUN mkdir common
COPY ./common/package*.json ./common

RUN cd ./common && npm install 

COPY . ./

RUN cd ./common && npm run share
RUN npm run relink:common

EXPOSE 3001

CMD [ "npm","run","dev" ]