apiVersion: v1
kind: Service
metadata:
  name: moove-places-srv
spec:
  type: ClusterIP
  selector:
    app: moove-places
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: moove-places-nodeport
spec:
  type: NodePort   
  selector:
    app: moove-places
  ports:
  - port: 3001       
    targetPort: 3001 
    protocol: TCP
    nodePort: 32001  
    
