apiVersion: v1
kind: ConfigMap
metadata:
  name: moove-places-db-init-script
data:
  init.js: |
    db.createUser({
      user: process.env.MONGO_INITDB_USERNAME,
      pwd: process.env.MONGO_INITDB_PASSWORD,
      roles: [
        {
          role: "readWrite",
          db: "placesdb"
        }
      ]
    });
