apiVersion: v1
kind: Service
metadata:
  name: moove-trips-srv
spec:
  type: ClusterIP
  selector:
    app: moove-trips
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: moove-trips-nodeport
spec:
  type: NodePort   
  selector:
    app: moove-trips
  ports:
  - port: 3001       
    targetPort: 3001 
    protocol: TCP
    nodePort: 32002

